# dmgbuild settings for the FPV DMG. Replaces the
# bundle_dmg.sh (create-dmg) call we used to make because that tool
# drives the layout via Finder AppleScript, which trips macOS
# Automation TCC and fails with `-1743` whenever the parent shell
# hasn't been explicitly granted "Finder" under Privacy → Automation.
# `dmgbuild` writes the icon positions and window geometry directly
# into the disk image's `.DS_Store` via the `ds_store` Python lib, so
# the same DMG layout works in a sandboxed CI shell, a freshly-cloned
# checkout, and an interactive Terminal — no system prompts.
#
# Invocation (see scripts/package.sh):
#   dmgbuild -s src-tauri/dmg/dmg-settings.py \
#     -D app=/abs/path/to/FPV.app \
#     -D bg=/abs/path/to/background.png \
#     "FPV" output.dmg

import os

# `-D app=...` and `-D bg=...` get injected as module-level names by
# dmgbuild's argument parser before this file executes. We fall back
# to lookups against the build tree only so the file is also runnable
# from the repo root for quick ad-hoc tests.
try:
    app_path = app  # noqa: F821 — provided by -D app=...
except NameError:
    app_path = os.path.abspath("src-tauri/target/aarch64-apple-darwin/release/bundle/macos/FPV.app")

try:
    bg_path = bg  # noqa: F821 — provided by -D bg=...
except NameError:
    bg_path = os.path.abspath("src-tauri/dmg/background.png")

format = "UDZO"
size = None  # let dmgbuild auto-size from contents
files = [app_path]
symlinks = {"Applications": "/Applications"}
hide_extension = [os.path.basename(app_path)]

icon_locations = {
    os.path.basename(app_path): (110, 150),
    "Applications": (380, 150),
}

background = bg_path

show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
sidebar_width = 180

# Window geometry in (x, y, w, h). Matches the 500×350 background
# generated by build-background.py — keep the two in sync (chevron is
# painted at the midpoint between icon slots).
window_rect = ((100, 100), (500, 350))
default_view = "icon-view"
show_icon_preview = False

include_icon_view_settings = "auto"
include_list_view_settings = "auto"

arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = "bottom"  # apple-style — name under icon
text_size = 12
icon_size = 128
